// ===== ТЕСТОВЫЙ ПОЛЬЗОВАТЕЛЬ =====
export const MOCK_USER = {
    id: 1,
    email: 'user@example.com',
    name: 'Иван Петров',
    position: 'Старший курьер',
    department: 'Отдел доставки',
    joinDate: '2023-01-15',
    daysInSystem: 680,
    completedRecommendations: 12,
    avatar: null,
};

// ===== ИСТОРИЯ ДИАГНОСТИК =====
export const MOCK_ASSESSMENT_HISTORY = [
    {
        id: 1,
        date: '2025-11-11',
        timestamp: '2025-11-11T10:30:00Z',
        burnoutLevel: 'medium',
        score: 62,
        emotionalExhaustion: 28,
        depersonalization: 16,
        reducedAccomplishment: 18,
        answers: {
            0: 3, 1: 4, 2: 3, 3: 4, 4: 2, 5: 3, 6: 4, 7: 3, 8: 4, 9: 3,
            10: 2, 11: 3, 12: 4, 13: 3, 14: 2, 15: 3, 16: 4, 17: 3, 18: 2, 19: 3,
        },
    },
    {
        id: 2,
        date: '2025-11-04',
        timestamp: '2025-11-04T14:20:00Z',
        burnoutLevel: 'high',
        score: 78,
        emotionalExhaustion: 35,
        depersonalization: 20,
        reducedAccomplishment: 23,
        answers: {
            0: 4, 1: 5, 2: 4, 3: 5, 4: 3, 5: 4, 6: 5, 7: 4, 8: 5, 9: 4,
            10: 3, 11: 4, 12: 5, 13: 4, 14: 3, 15: 4, 16: 5, 17: 4, 18: 3, 19: 4,
        },
    },
    {
        id: 3,
        date: '2025-10-28',
        timestamp: '2025-10-28T09:15:00Z',
        burnoutLevel: 'high',
        score: 82,
        emotionalExhaustion: 37,
        depersonalization: 22,
        reducedAccomplishment: 23,
        answers: {
            0: 5, 1: 5, 2: 4, 3: 5, 4: 4, 5: 5, 6: 5, 7: 4, 8: 5, 9: 4,
            10: 4, 11: 4, 12: 5, 13: 4, 14: 4, 15: 4, 16: 5, 17: 4, 18: 4, 19: 4,
        },
    },
    {
        id: 4,
        date: '2025-10-21',
        timestamp: '2025-10-21T11:45:00Z',
        burnoutLevel: 'medium',
        score: 65,
        emotionalExhaustion: 29,
        depersonalization: 17,
        reducedAccomplishment: 19,
        answers: {
            0: 3, 1: 4, 2: 3, 3: 4, 4: 3, 5: 3, 6: 4, 7: 3, 8: 4, 9: 3,
            10: 3, 11: 3, 12: 4, 13: 3, 14: 3, 15: 3, 16: 4, 17: 3, 18: 3, 19: 3,
        },
    },
    {
        id: 5,
        date: '2025-10-14',
        timestamp: '2025-10-14T16:00:00Z',
        burnoutLevel: 'low',
        score: 45,
        emotionalExhaustion: 20,
        depersonalization: 11,
        reducedAccomplishment: 14,
        answers: {
            0: 2, 1: 3, 2: 2, 3: 3, 4: 2, 5: 2, 6: 3, 7: 2, 8: 3, 9: 2,
            10: 2, 11: 2, 12: 3, 13: 2, 14: 2, 15: 2, 16: 3, 17: 2, 18: 2, 19: 2,
        },
    },
];

// ===== МЕТРИКИ ДЛЯ ДАШБОРДА (ПОСЛЕДНИЕ 7 ДНЕЙ) =====
export const MOCK_DASHBOARD_METRICS = [
    { date: 'Пн', burnout: 82, stress: 85, productivity: 18 },
    { date: 'Вт', burnout: 78, stress: 80, productivity: 22 },
    { date: 'Ср', burnout: 75, stress: 78, productivity: 25 },
    { date: 'Чт', burnout: 70, stress: 72, productivity: 30 },
    { date: 'Пт', burnout: 65, stress: 68, productivity: 35 },
    { date: 'Сб', burnout: 62, stress: 65, productivity: 38 },
    { date: 'Вс', burnout: 62, stress: 63, productivity: 38 },
];

// MOCK данные для начальника
export const MOCK_MANAGER = {
    id: 2,
    name: 'Петров Иван Сергеевич',
    email: 'manager@cdek.ru',
    position: 'Менеджер отдела',
    department: 'Доставка',
    role: 'manager', // начальник
    joinDate: '2020-03-10',
    daysInSystem: 1710,
    completedRecommendations: 45,
};

// MOCK данные подчиненных
export const MOCK_TEAM_MEMBERS = [
    {
        id: 3,
        name: 'Иванова Мария Петровна',
        email: 'ivanova@cdek.ru',
        position: 'Курьер',
        department: 'Доставка',
        burnoutLevel: 'high',
        burnoutScore: 78,
        lastTestDate: '2025-11-14',
        emotionalExhaustion: 85,
        depersonalization: 70,
        reducedAccomplishment: 80,
        recommendationsCompleted: 3,
        recommendationsTotal: 15,
        status: 'critical',
        trend: 'increasing',
    },
    {
        id: 4,
        name: 'Сидоров Алексей Викторович',
        email: 'sidorov@cdek.ru',
        position: 'Курьер',
        department: 'Доставка',
        burnoutLevel: 'medium',
        burnoutScore: 52,
        lastTestDate: '2025-11-13',
        emotionalExhaustion: 55,
        depersonalization: 48,
        reducedAccomplishment: 53,
        recommendationsCompleted: 8,
        recommendationsTotal: 12,
        status: 'warning',
        trend: 'stable',
    },
    {
        id: 5,
        name: 'Кузнецова Елена Дмитриевна',
        email: 'kuznetsova@cdek.ru',
        position: 'Курьер',
        department: 'Доставка',
        burnoutLevel: 'low',
        burnoutScore: 28,
        lastTestDate: '2025-11-15',
        emotionalExhaustion: 25,
        depersonalization: 30,
        reducedAccomplishment: 29,
        recommendationsCompleted: 10,
        recommendationsTotal: 10,
        status: 'good',
        trend: 'decreasing',
    },
    {
        id: 6,
        name: 'Смирнов Дмитрий Андреевич',
        email: 'smirnov@cdek.ru',
        position: 'Курьер',
        department: 'Доставка',
        burnoutLevel: 'high',
        burnoutScore: 82,
        lastTestDate: '2025-11-12',
        emotionalExhaustion: 88,
        depersonalization: 75,
        reducedAccomplishment: 83,
        recommendationsCompleted: 2,
        recommendationsTotal: 15,
        status: 'critical',
        trend: 'increasing',
    },
    {
        id: 7,
        name: 'Волкова Анна Сергеевна',
        email: 'volkova@cdek.ru',
        position: 'Курьер',
        department: 'Доставка',
        burnoutLevel: 'medium',
        burnoutScore: 45,
        lastTestDate: '2025-11-14',
        emotionalExhaustion: 48,
        depersonalization: 42,
        reducedAccomplishment: 46,
        recommendationsCompleted: 7,
        recommendationsTotal: 12,
        status: 'warning',
        trend: 'stable',
    },
];
